create type "public"."race_status" as enum ('waiting', 'started', 'finished');

create table "public"."profiles" (
    "id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "username" text not null,
    "is_guest" boolean default false
);
    
alter table "public"."profiles" enable row level security;

create table "public"."races" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "sentence_id" bigint not null,
    "start_time" timestamp with time zone,
    "end_time" timestamp with time zone,
    "status" race_status not null default 'waiting'::race_status
);

alter table "public"."races" enable row level security;

create table "public"."race_players" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "race_id" uuid not null,
    "current_text" text not null default ''::text,
    "wpm" numeric not null default '0'::numeric,
    "accuracy" numeric not null default '0'::numeric,
    "is_finished" boolean not null default false,
    "username" text not null,
    unique (user_id, race_id)
);

alter table "public"."race_players" enable row level security;

create table "public"."sentences" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "text" text not null
);

alter table "public"."sentences" enable row level security;

create table "public"."stats" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "total_races" bigint not null default '0'::bigint,
    "avg_wpm" numeric not null default '0'::numeric,
    "avg_accuracy" numeric not null default '0'::numeric
);

alter table "public"."stats" enable row level security;

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username);

CREATE UNIQUE INDEX race_players_pkey ON public.race_players USING btree (id);

CREATE UNIQUE INDEX races_pkey ON public.races USING btree (id);

CREATE UNIQUE INDEX sentences_pkey ON public.sentences USING btree (id);

CREATE UNIQUE INDEX stats_pkey ON public.stats USING btree (id);

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."race_players" add constraint "race_players_pkey" PRIMARY KEY using index "race_players_pkey";

alter table "public"."races" add constraint "races_pkey" PRIMARY KEY using index "races_pkey";

alter table "public"."sentences" add constraint "sentences_pkey" PRIMARY KEY using index "sentences_pkey";

alter table "public"."stats" add constraint "stats_pkey" PRIMARY KEY using index "stats_pkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

alter table "public"."race_players" add constraint "race_players_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."race_players" add constraint "race_players_race_id_fkey" FOREIGN KEY (race_id) REFERENCES races(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."race_players" validate constraint "race_players_user_id_fkey";

alter table "public"."races" add constraint "races_sentence_id_fkey" FOREIGN KEY (sentence_id) REFERENCES sentences(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."races" validate constraint "races_sentence_id_fkey";

alter table "public"."stats" add constraint "stats_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."stats" validate constraint "stats_user_id_fkey";

set check_function_bodies = off;

create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, is_guest)
  values (new.id, 'guest_' || substr(md5(random()::text), 1, 6), true);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."race_players" to "anon";

grant insert on table "public"."race_players" to "anon";

grant references on table "public"."race_players" to "anon";

grant select on table "public"."race_players" to "anon";

grant trigger on table "public"."race_players" to "anon";

grant truncate on table "public"."race_players" to "anon";

grant update on table "public"."race_players" to "anon";

grant delete on table "public"."race_players" to "authenticated";

grant insert on table "public"."race_players" to "authenticated";

grant references on table "public"."race_players" to "authenticated";

grant select on table "public"."race_players" to "authenticated";

grant trigger on table "public"."race_players" to "authenticated";

grant truncate on table "public"."race_players" to "authenticated";

grant update on table "public"."race_players" to "authenticated";

grant delete on table "public"."race_players" to "service_role";

grant insert on table "public"."race_players" to "service_role";

grant references on table "public"."race_players" to "service_role";

grant select on table "public"."race_players" to "service_role";

grant trigger on table "public"."race_players" to "service_role";

grant truncate on table "public"."race_players" to "service_role";

grant update on table "public"."race_players" to "service_role";

grant delete on table "public"."races" to "anon";

grant insert on table "public"."races" to "anon";

grant references on table "public"."races" to "anon";

grant select on table "public"."races" to "anon";

grant trigger on table "public"."races" to "anon";

grant truncate on table "public"."races" to "anon";

grant update on table "public"."races" to "anon";

grant delete on table "public"."races" to "authenticated";

grant insert on table "public"."races" to "authenticated";

grant references on table "public"."races" to "authenticated";

grant select on table "public"."races" to "authenticated";

grant trigger on table "public"."races" to "authenticated";

grant truncate on table "public"."races" to "authenticated";

grant update on table "public"."races" to "authenticated";

grant delete on table "public"."races" to "service_role";

grant insert on table "public"."races" to "service_role";

grant references on table "public"."races" to "service_role";

grant select on table "public"."races" to "service_role";

grant trigger on table "public"."races" to "service_role";

grant truncate on table "public"."races" to "service_role";

grant update on table "public"."races" to "service_role";

grant delete on table "public"."sentences" to "anon";

grant insert on table "public"."sentences" to "anon";

grant references on table "public"."sentences" to "anon";

grant select on table "public"."sentences" to "anon";

grant trigger on table "public"."sentences" to "anon";

grant truncate on table "public"."sentences" to "anon";

grant update on table "public"."sentences" to "anon";

grant delete on table "public"."sentences" to "authenticated";

grant insert on table "public"."sentences" to "authenticated";

grant references on table "public"."sentences" to "authenticated";

grant select on table "public"."sentences" to "authenticated";

grant trigger on table "public"."sentences" to "authenticated";

grant truncate on table "public"."sentences" to "authenticated";

grant update on table "public"."sentences" to "authenticated";

grant delete on table "public"."sentences" to "service_role";

grant insert on table "public"."sentences" to "service_role";

grant references on table "public"."sentences" to "service_role";

grant select on table "public"."sentences" to "service_role";

grant trigger on table "public"."sentences" to "service_role";

grant truncate on table "public"."sentences" to "service_role";

grant update on table "public"."sentences" to "service_role";

grant delete on table "public"."stats" to "anon";

grant insert on table "public"."stats" to "anon";

grant references on table "public"."stats" to "anon";

grant select on table "public"."stats" to "anon";

grant trigger on table "public"."stats" to "anon";

grant truncate on table "public"."stats" to "anon";

grant update on table "public"."stats" to "anon";

grant delete on table "public"."stats" to "authenticated";

grant insert on table "public"."stats" to "authenticated";

grant references on table "public"."stats" to "authenticated";

grant select on table "public"."stats" to "authenticated";

grant trigger on table "public"."stats" to "authenticated";

grant truncate on table "public"."stats" to "authenticated";

grant update on table "public"."stats" to "authenticated";

grant delete on table "public"."stats" to "service_role";

grant insert on table "public"."stats" to "service_role";

grant references on table "public"."stats" to "service_role";

grant select on table "public"."stats" to "service_role";

grant trigger on table "public"."stats" to "service_role";

grant truncate on table "public"."stats" to "service_role";

grant update on table "public"."stats" to "service_role";